name: store-cars-github-workflow
run-name: ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Action checkout with setup java 17'
        uses: actions/checkout@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - run: chmod +x ./gradlew && ./gradlew clean build