name: store-cars-github-workflow
run-name: ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Setup Java 17'
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - run: chmod +x ./gradlew && ./gradlew clean build